LineageOS-20:
  kernel:
    - git clone https://github.com/a02-trial/BR_kernel_a02.git -b kernelku
  clang:
    - git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git -b lineage-19.1
  config:
    - make O=out ARCH=arm a02_defconfig
  build:
    - ARCH=arm CC=clang HOSTCC=clang CROSS_COMPILE="${PWD}/arm-linux-androideabi-" CLANG_TRIPLE=arm-linux-gnueabi- make -j$(nproc --all) O=out
  target:
    - out/arch/arm/boot/zImage
  anykernel:
    - nashc
  kernelSU:
    - stable-pin

Clean:
  out:
    - rm -rf out
  kernel:
    - make mrproper
  custom:
    - git status

# Stable-pin version of KernelSU is used by KernelSU.sh to replace placeholder (kernelsu-version) with the newest stable version from ksu_version.txt
KernelSU:
  version:
    stable-pin:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
    stable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
    unstable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

AnyKernel3:
  version:
    nashc:
      - git clone https://github.com/HowWof/AnyKernel3.git -b master
    test:
      - echo "Test Success!"
